# Creating an array with a specific dtype

In [49]:
my_arr=mynp.arange(1,11,dtype=float).reshape(10,1)
print(my_arr)
print(my_arr.dtype)
print(my_arr.shape)
my_arr=mynp.arange(1,101,dtype=object).reshape(10,10)
print(my_arr)
print(my_arr.dtype)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
float64
(10, 1)
[[1 2 3 4 5 6 7 8 9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99 100]]
object


# Array Creation using linspace() function

linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)
start:the number with which it starts(optional), default=0 
Stop:end point of interval rannge.
num:indicates the number of samples to generate.
endpoint:if set to False, the stop value is excluded and when rue, it is included.
retstep: spacing or steps between the value.
dtype: specifies the output array type.

In [65]:
import numpy as mynp
print(mynp.linspace(0,2))
print('-------------'*5)
print(mynp.linspace(0,2,3))
print('-------------'*5)
print(mynp.linspace(0,5,5,endpoint=False))
print('-------------'*5)
print(mynp.linspace(1,5,5,endpoint=True))
print('-------------'*5)
print(mynp.linspace(0,5,5,endpoint=False,retstep=True))
print('-------------'*5)
print(mynp.linspace(0,5,5,endpoint=False,retstep=True,dtype=int))

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]
-----------------------------------------------------------------
[0. 1. 2.]
-----------------------------------------------------------------
[0. 1. 2. 3. 4.]
-----------------------------------------------------------------
[1. 2. 3. 4. 5.]
-----------------------------------------------------------------
(array([0., 1., 2., 3., 4.]), np.float64(1.0))
-----------------------------------------------------------------
(array([0, 1, 2, 3

 this means arange()- elemnts within a specified range but linspace() - considers specified number of values within a given range
 0D= scalar 
 1D= A collection of 0D arrays, k/a vectors
 2D= consists 1D arrays containing 20 elements
 3D arrays= Reps a 1D containing 20 elements
 (20,): Reps 1D array of 20 elements
 (10,2): Reps a 2D array with ten rows and 2 columns
 (1,2,3): reps a 3d array which has:
    - one set of 2D arrays,
    - Each 2D array contains 2 rows
    - Each 2D array comprises three columns
    - Size calculation: 1*2*3=6

# Utilizing the zeros() function in numpy

In [91]:
# creating 1 D array of zeros
print(mynp.zeros((4)))              #1D
print('-------------'*5)
print(mynp.zeros((4,4)))            #2D
print('-------------'*5)
print(mynp.zeros((2,4,4)))          #3D
print('-------------'*5)
print(mynp.zeros((4,4,4,4)))        #4D

[0. 0. 0. 0.]
-----------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------------------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----------------------------------------------------------------
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0

# Utilizing the ones() function in numpy

In [98]:
# similar to zeros()
import numpy as np
# 1D
print(np.ones((4)))
print('-------------'*5)
print(np.ones((3,3)))
print('-------------'*5)
print(np.ones((2,3,3)))
print('-------------'*5)
print(np.ones((2,2,3,3)))

[1. 1. 1. 1.]
-----------------------------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------------------------------------------------------
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
-----------------------------------------------------------------
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]


# Utilizing the full() function in numpy
 - full function - new array with specific shape and data type, filled with a specific fill value. 

In [10]:
# full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)
#   Return a new array of given shape and type, filled with `fill_value`.

import numpy as np
arr=np.full((3,3),1,dtype=float,order='C')
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# Creating 1D
import numpy as np
print(np.full((4,4),fill_value=4))
print('------------'*5)
print(np.full((3,2,2),fill_value=2))
print('------------'*5)
print(help(np.full))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
------------------------------------------------------------
[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]

 [[2 2]
  [2 2]]]
------------------------------------------------------------
Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with `fill_value`.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For

# Using eye() function
eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
    
    Return a 2-D array with ones on the diagonal and zeros elsewhere.


In [38]:
import numpy as np
print(np.eye(10,k=7))
print('------------'*5)
print(np.eye(3,k=1))
print('------------'*5)
print(np.eye(4,k=-3))
print(help(np.eye))

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
------------------------------------------------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagona

# Utilizing diag() function
diag(v, k=0)
    Extract a diagonal or construct a diagonal array.

In [25]:
import numpy as np
print(help(np.diag))

Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.

    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.

    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.

    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.

    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input as a 

In [ ]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
# Extracting diagonals
print(f"diagonal= {np.diag(arr)}")
print("-------"*5)
print(f"diagonal= {np.diag(arr,k=1)}")
print(f"diagonal= {np.diag(arr,k=2)}")
print(f"diagonal= {np.diag(arr,k=3)}")
print(f"diagonal= {np.diag(arr,k=4)}")
print("-------"*5)
print(f"diagonal= {np.diag(arr,k=-4)}")
print(f"diagonal= {np.diag(arr,k=-3)}")
print(f"diagonal= {np.diag(arr,k=-2)}")
print(f"diagonal= {np.diag(arr,k=-1)}")
print("-------"*5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
diagonal= [ 1  7 13 19 25]
-----------------------------------
diagonal= [ 2  8 14 20]
diagonal= [ 3  9 15]
diagonal= [ 4 10]
diagonal= [5]
-----------------------------------
diagonal= [21]
diagonal= [16 22]
diagonal= [11 17 23]
diagonal= [ 6 12 18 24]
-----------------------------------


In [23]:
# 1-D construct a 2-D array using the provided 
# elements and a diagonal array;
arr1=np.array([1,2,3,4,5,6])
print(np.diag(arr1,k=0).reshape(6,6)) #the remaining elemments are filled by the zeros
print("-------"*5)
print(np.diag(arr1,k=1))
print("-------"*5)
print(np.diag(arr1,k=-1))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
-----------------------------------
[[0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]
 [0 0 0 0 0 0 0]]
-----------------------------------
[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


# Utilizing empty() function
empty(...)
    empty(shape, dtype=float, order='C', *, device=None, like=None)

    Return a new array of given shape and type, without initializing entries.


In [24]:
import numpy as np
print(help(np.empty))

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, device=None, like=None)

    Return a new array of given shape and type, without initializing entries.

    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: ``None``.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-l

In [32]:
# generates a new arraty with specified shape and data type without intializing entries.
# basically creates a dummy array.
# its use- to quickly just create any array by defining its shape and dtype. (mostly garbage values)
# used when setting of values is unnecessary.
import numpy as np
print(np.empty((2,2),dtype=int))

[[25895968444448860 23925768161198147]
 [32370111954616435 32933044727906396]]


# Contrast between zeros and empty function:
 - choose zeros() when array filled with zeros required.
 - choose empty() if array is required without any pre set values or uninitialized values. 
 - creation of an array with empty is significantly faster compared to zeros(). 

# Using random module for ndarray creation
 creates array with random data.with functions like randint and shuffle functions.

## Randint()
rand-- random
int-- integers
random integers within a range.

mynp.random.randint(low, high=None, size=None, 
dtype=int)

In [58]:
import numpy as np
arr=np.random.randint(1,101, size=(5,5))
print(arr)


[[ 12  87   7  96  28]
 [ 32  53  25  46 100]
 [100  65  75  17  53]
 [ 53  20  55  16  91]
 [ 59  61  81   2  78]]


## Shuffle()
it shuffles array along axis-0. corresponds to the first axis in a multi dimensional array. 


In [69]:
import numpy as np
print(help(np.random.shuffle))

Help on method shuffle in module numpy.random:

shuffle(x) method of numpy.random.mtrand.RandomState instance
    shuffle(x)

    Modify a sequence in-place by shuffling its contents.

    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.

    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.

    Returns
    -------
    None

    See Also
    --------
    random.Generator.shuffle: which should be used for new code.

    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random

    Multi-dimensional arrays are only shuffled along the firs

### Shuffling of 1D array

In [73]:
arr=np.arange(16)
print('arr before shuffle- ')
print(arr)
print('----------'*5)
np.random.shuffle(arr)        # shuffle inside a row
print('arr after shuffle- ')
print(arr)
print('----------'*5)

arr before shuffle- 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
--------------------------------------------------
arr after shuffle- 
[ 1 15 13  0  6  7  5  3 11  9 12 14  4 10  8  2]
--------------------------------------------------


### Shuffling of 2-D arrays

In [82]:
arr= np.arange(25).reshape(5,5)
print('arr before shuffle- ')
print(arr)
print('arr after shuffle- ')
np.random.shuffle(arr)               # shuffle between rows not in a row
print(arr)

arr before shuffle- 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
arr after shuffle- 
[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]


# Some additional functions of random()
## 1.rand()- generates uniformly distributed 'float' values in range(0,1)

## 2.uniform()-generates uniformly distributed 'float' values in range(low,high)

## 3.randn()- generates normally distributed float values with a mean of zero and a standard deviation of one.
### What this looks like in practice:
When you call randn() repeatedly, you'll get values that are mostly clustered around 0, with these probabilities:
About 68% of values will be between -1 and +1
About 95% of values will be between -2 and +2
About 99.7% of values will be between -3 and +3

### It's commonly used for:
Adding noise to data
Initializing neural network weights
Statistical simulations
Testing algorithms with realistic random variations

## 4.normal()- generates normally distributed float values with a specified mean and a stamndard deviation.
The normal() function generates random numbers from a normal (Gaussian) distribution where you specify both the mean and standard deviation yourself.
### Syntax:
normal(mean, standard_deviation, size=None)
### Key difference from randn():
randn() = fixed mean=0, std=1
normal() = you choose the mean and std
### Common use cases:
- Simulating real-world data: heights, weights, test scores
- Adding specific noise: sensor readings with known error margins
- Financial modeling: returns with specific volatility
- Scientific simulations: measurements with known uncertainty

# Exploring differences between View vs. Copy in numpy
## View-
- logical rep of existing array(not different object)
- changes made apply to original array and vice versa
## Copy-
- its a seperate object
- changes to object dont apply on the original and vice versa.

# Elements access of ndarray
elements of ndarray can be accessed using 
- indexing
- slicing
- condition based selection
- advanced indexing

In [106]:
arr=np.random.randint(1,100,size=(3,3,3))  # a 3D array
print(arr)
print("-----------"*5)
# 1. Using indexing: single element access, zero based indexing supporting both +ve and -ve
print(f"arr[0][0][1]={arr[0][0][1]}")
print(f"arr[2][2][2]={arr[2][2][2]}")
print("-----------"*5)
# 2. Using slicing: 
print("last element of all matrices =")
print(f"{arr[:,2:,2:]}")
print("-----------"*5)

[[[83 15 57]
  [89 40 83]
  [99 16 57]]

 [[40 94 72]
  [11 79 95]
  [ 2 41 16]]

 [[76 63 44]
  [96 30 13]
  [55 78  5]]]
-------------------------------------------------------
arr[0][0][1]=15
arr[2][2][2]=5
-------------------------------------------------------
last element of all matrices =
[[[57]]

 [[16]]

 [[ 5]]]
-------------------------------------------------------


# 3. Using advanced indexing: 
- Integer indexing
- Boolean indexing
## Integer indexing
 ----- Syntax: arr[[2-D array indices],[row indices],[column indices]]
 its like a(i,j) we learnt in matrix-the ( element index ).this is true for 2D arrays.
 for 3D array just one more index comes, i.e. the 2D array index before (i,j)-- i.e. (2D-array-index, i, j) 

In [117]:
arr3d=np.arange(27).reshape(3,3,3)
print(arr3d)
print("-------"*5)
print(arr3d[([0,1],[1,2],[1,2])])
# this array returned contains elements: 
# [(0 position 3D array, 1st row x 1st column),
# (1 position 3D array, 2nd row x 2nd column)]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------------
[ 4 17]


## Boolean indexing

In [137]:
arr3d=np.arange(27).reshape(3,3,3)
print(arr3d)
print("-------"*5)
print(arr3d>5)              # A bollean array of true and false for fuklfilling conditions
print("-------"*5)
print(arr3d[arr3d>5])        # gives the 1D-array of elements fulfilling the condition
print("-------"*5)
# To retain the shape of the array and not let it convert to 1D array use where method
print(np.where(arr3d>5,arr3d,0))  # 1st value- condition, 2nd value- what to return if condition is true, 3rd value- what to return if condition false
print("-------"*5)
# To apply multiple conditions to array use: logical_and
print(np.logical_and(arr3d>5,arr3d<24))
print("-------"*5)
# to print the array with multiple conditions:
conditions=np.logical_and(arr3d>5,arr3d<24)
print(arr3d[conditions])    # returns a 1D-array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------------
[[[False False False]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
-----------------------------------
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
-----------------------------------
[[[ 0  0  0]
  [ 0  0  0]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------------
[[[False False False]
  [False False False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [False False False]]]
-----------------------------------
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Iterate elements of ndarray
- Iteration using Python loop
- Iteration using nditer() function:
- Iteration using ndenumerate() function

## 1.Iteration using Python loop

In [141]:
# 3D-Array
import numpy as np
arr=np.arange(27).reshape(3,3,3)
print(arr)
print("-------"*5)
for outer in arr:  # iterating 2D arrey
    for inner in outer:  # iterating 1D array
        for data in inner:  # Iterating through scalar values in 1D array
            print(data)
print("-------"*5)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-----------------------------------
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## 2. Iteration using nditer() function:

In [145]:
import numpy as np
arr=np.arange(1,7).reshape(2,3)
print(arr)
print("-------"*5)
for loop in np.nditer(arr):
    print(loop)
print("-------"*5)

[[1 2 3]
 [4 5 6]]
-----------------------------------
1
2
3
4
5
6
-----------------------------------


## 3.Iteration using ndenumerate() function

In [146]:
import numpy as np
# this funtion returns indexes in addition to elements as multidimensional
for myposition,myvalue in np.ndenumerate(arr):
    print(f"{myvalue} is on position:{myposition}")
    

1 is on position:(0, 0)
2 is on position:(0, 1)
3 is on position:(0, 2)
4 is on position:(1, 0)
5 is on position:(1, 1)
6 is on position:(1, 2)


# Arithmetic operators in numpy

In [159]:
import numpy as np
arr1=np.random.randint(1,10,size=(3,3))
arr2=np.random.randint(11,20,size=(3,3))
print(f"arr1 :\n{arr1}")
print(f"arr2 :\n{arr2}")
print("-----------"*5)
# size
print(f"size arr1={arr1.size}")
print(f"size arr2= {arr2.size}")
# shape
print(f"shape arr1= {arr1.shape}")
print(f"shape arr2= {arr2.shape}")
# dimension
print(f"dimension arr1= {arr1.ndim}")
print(f"dimension arr2= {arr2.ndim}")

arr1 :
[[8 3 2]
 [8 3 8]
 [6 4 7]]
arr2 :
[[19 11 14]
 [14 15 12]
 [16 13 19]]
-------------------------------------------------------
size arr1=9
size arr2= 9
shape arr1= (3, 3)
shape arr2= (3, 3)
dimension arr1= 2
dimension arr2= 2


In [161]:
import numpy as np
# Addition
print(f"Addition of arr1,arr2=\n {np.add(arr1,arr2)}")
# Subtraction
print(f"Subtraction of arr1,arr2=\n {np.subtract(arr1,arr2)}")
# Multiplication
print(f"Multiplication of arr1,arr2=\n {np.multiply(arr1,arr2)}")
# Division
print(f"Division of arr1,arr2=\n {np.divide(arr1,arr2)}")
# Floor Division
print(f"Floor Division of arr1,arr2=\n {np.floor_divide(arr1,arr2)}")
# Modulus
print(f"Modulus of arr1,arr2=\n {np.mod(arr1,arr2)}")
# Power
print(f"arr1 power arr2=\n {np.power(arr1,arr2)}")

Addition of arr1,arr2=
 [[27 14 16]
 [22 18 20]
 [22 17 26]]
Subtraction of arr1,arr2=
 [[-11  -8 -12]
 [ -6 -12  -4]
 [-10  -9 -12]]
Multiplication of arr1,arr2=
 [[152  33  28]
 [112  45  96]
 [ 96  52 133]]
Division of arr1,arr2=
 [[0.42105263 0.27272727 0.14285714]
 [0.57142857 0.2        0.66666667]
 [0.375      0.30769231 0.36842105]]
Floor Division of arr1,arr2=
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Modulus of arr1,arr2=
 [[8 3 2]
 [8 3 8]
 [6 4 7]]
arr1 power arr2=
 [[         0     177147      16384]
 [         0   14348907          0]
 [-683606016   67108864  442181591]]


# Broadcasting concept in numpy