# Array manipulation functions/variables in numpy

- Imp for efficient data manipulation and analysis
- tools necessary for reshaping, concatenating, or splitting along specific axes, transposing and extracting information about array dimensions and shapes.
- helps in tasks :
   - data preprocessing
   - image processing
   - numerical simulations
   - statistical analysis
   - enables streamlinged and optimized manipulation of array data structure.

# reshape()

- changes array shape without swapping data.
- sizes must be matched or else- ValueError
- here view is created instead of copy - changes in reshaped array seen in original
- syntax: np.reshape(arr,newshape,order='C') or arr.reshape(newshape,order='C')

In [16]:
import numpy as np
arr1=np.arange(6)
arr2=arr1.reshape(2,3)
print(arr1)
print("-"*50)
print(arr2)
# modifying the 2nd index value of original array
print("-"*50)
arr1[1]=12
print(f"modified 2nd index value of arr1 : {arr1}")
print(f"arr2 is now {arr2}")
# F style order
arr3= np.arange(16,32)
arr4=arr3.reshape((4,4), order='F')
print(f"arr3 is : {arr3}")
print(f"arr4 is : {arr4}")

[0 1 2 3 4 5]
--------------------------------------------------
[[0 1 2]
 [3 4 5]]
--------------------------------------------------
modified 2nd index value of arr1 : [ 0 12  2  3  4  5]
arr2 is now [[ 0 12  2]
 [ 3  4  5]]
arr3 is : [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
arr4 is : [[16 20 24 28]
 [17 21 25 29]
 [18 22 26 30]
 [19 23 27 31]]


# resize()

- resizes an array to a specified shape which can increase or decrease array size
- 2 ways...
    - functional style
    - object oriented style

## Functional Style (repeating elements if needed)

In [36]:
import numpy as np
# functional style creates a new object
# original array
arr= np.array([1,2,3,4,5,6])

# while increasing size it repeats elements
new_arr=np.resize(arr,(8,))    # a new object is created
print(f"arr after increasing size: {new_arr}")          # 1,2 added(repeated) to resize 
print("-"*50)
# while reducing size, data is lost.... 
smaller_arr=np.resize(arr,(4,))
print(f"smaller arr: {smaller_arr}")     # reduced size of arr
print(f"original arr: {arr}")        # no changes in original
print("-"*50)
# for 2D-array
arr_2d=np.arange(4).reshape(2,2)
new_arr_2d=np.resize(arr_2d,(3,3))
print(f"new 2d arr: {new_arr_2d}")

arr after increasing size: [1 2 3 4 5 6 1 2]
--------------------------------------------------
smaller arr: [1 2 3 4]
original arr: [1 2 3 4 5 6]
--------------------------------------------------
new 2d arr: [[0 1 2]
 [3 0 1]
 [2 3 0]]


## Object oriented style (ndarray.resize)

##### for 1D-array

In [37]:
import numpy as np
# original array
arr= np.array([1,2,3,4,5])

# a view is creates hence, the change is seen in original as well
# while increasing size - instead of repeating it fills the array with 0s
arr.resize(8,refcheck=False)   # fills with 0 and directly makes changes in the original
print(arr)   # array filled with 0s to make it of size 8
print("-"*50)

# in object oriented style return value is None
new_arr=we

[1 2 3 4 5 0 0 0]
--------------------------------------------------


##### for 2D-array

In [10]:
import numpy as np
arr_2d=np.arange(1,10).reshape((3,3)).copy()
print(f"arr: {arr_2d}")
print("-"*50)
arr_2d.resize((4,4),refcheck=False)        # arr_2d is a copy, thats why it gets resized otherwise it would have raised ValueError- 
                                           # by saying that it dosent own its data
print(arr_2d)

arr: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]
 [0 0 0 0]]


# flatten()

##### included elements of a given multidimensional array that will create a new 1D array.
returned value: a copy of the collapsed array

* not a numpy function but present method in ndarray class
* always returns a copy
* owns its own data
* can specify order('C'/'F'/'A'/'K')
* it flattens 2D, 3D, 1D similarly converting them to 1D array
     - 'A'- preserves original order
     - 'K'- preserves order as in memory
     - 'F'- column major(Fortran style)- traverse column first
     - 'C'- (default) Row major (C- Style)- traverse rows first
syntax: ndarray.flatten(order='C'(default))

In [21]:
import numpy as np

# flattening with default order= 'C'
arr1=np.arange(1,7).reshape(2,3)
arr2=arr1.flatten()
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print("-"*50)
# change in the original array will not affect the flattened array.
arr1[0,0]=23
print(f"changed original array: {arr1}")
print(f"flattened array remained same: {arr2}")
print("-"*50)
# flattening with order='F'
arr1[0,0]=1
arr3=arr1.flatten('F')
print(f"arr3 made by order 'F': {arr3}")

arr1: [[1 2 3]
 [4 5 6]]
arr2: [1 2 3 4 5 6]
--------------------------------------------------
changed original array: [[23  2  3]
 [ 4  5  6]]
flattened array remained same: [1 2 3 4 5 6]
--------------------------------------------------
arr3 made by order 'F': [1 4 2 5 3 6]


# flat variable

##### It is a 1D iterator ovetr the array which will allow to access the elements of 
##### a multidimensional array
##### syntax: ndarray.flat

In [ ]:
import numpy as np
arr1=np.arange(1,7).reshape(2,3)
print(f"arr1: {arr1}")
print("-"*50)

print(arr1.flat)

#iterating
for element in arr1.flat:
    print(element)

# Indexing with flat
arr_2d=np.arange(1,5).reshape(2,2)
print(arr_2d)
print("-"*50)

#### Key Features-

#### Indexing

In [31]:
print(f" element 1 : {arr_2d.flat[0]}")     # indexing with flat singularly
print(f" element 2 : {arr_2d.flat[1]}")     # indexing with flat singularly        
print(f" element 3 : {arr_2d.flat[2]}")     # indexing with flat singularly
print(f" element 4 : {arr_2d.flat[3]}")     # indexing with flat singularly

print(f"elements 1,3 and 4th: {arr_2d.flat[[0,2,3]]}")  # indexing and getting multiple values

 element 1 : 1
 element 2 : 2
 element 3 : 3
 element 4 : 4
elements 1,3 and 4th: [1 3 4]


#### Assignment with flat

In [40]:
import numpy as np
arr_2d=np.arange(1,10).reshape(3,3)
print(arr_2d)
print("-"*50)

# Modifying elements using flat:
arr_2d.flat[2]=333
print(arr_2d)
print("-"*50)
arr_2d.flat[[0,6,8]]=[111,777,999]
print(arr_2d)
print("-"*50)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[  1   2 333]
 [  4   5   6]
 [  7   8   9]]
--------------------------------------------------
[[111   2 333]
 [  4   5   6]
 [777   8 999]]
--------------------------------------------------


#### Slicing with flat

In [44]:
import numpy as np
arr_2d=np.arange(1,10).reshape(3,3)
print(arr_2d)
print("-"*50)

# getting elements with step count 2:
print(arr_2d.flat[::2])
print("-"*50)

# getting a slice:
print(arr_2d.flat[5:8])
print("-"*50)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[1 3 5 7 9]
--------------------------------------------------
[6 7 8]
--------------------------------------------------


# ravel()

similar to flatten method but it returns a view rather than a copy
any changes in the original affect the ravel view. and vice versa.
- it is memory efficient
- may return copy if array is non contiguous
  
syntax: np.ravel(arr, order='C')

or

arr.ravel(order='C')

In [53]:
import numpy as np
arr1= np.arange(1,10).reshape(3,3)
print(arr1)
print("-"*50)

# Ravel to 1D
ravel_arr1=arr1.ravel()
print(f"arr1: {arr1}")
print(f"Raveled arr1: {ravel_arr1}")
print("-"*50)

# proof of it being a view and not a copy
arr1[0,0]=111111
print(arr1)
print(ravel_arr1)
print("-"*50)

# vice-versa:
ravel_arr1[1]=222222
print(arr1)
print(ravel_arr1)
print("-"*50)

# When does ravel return a copy and a view ????
# contiguous array(C-order)- returns view
contiguous_c = np.array([[1,2,3],[4,5,6]])
ravel_c = contiguous_c.ravel() # This returns a view and not a copy
# even with order='F' if the array is contiguous then it returns a view and not a copy
# Copy is returned only when the array is non-contiguous
# Here order paramenters work similar to flat or flatten method

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
arr1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Raveled arr1: [1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[[111111      2      3]
 [     4      5      6]
 [     7      8      9]]
[111111      2      3      4      5      6      7      8      9]
--------------------------------------------------
[[111111 222222      3]
 [     4      5      6]
 [     7      8      9]]
[111111 222222      3      4      5      6      7      8      9]


# Contiguity
#### Now what does it mean by contiguous: ???
it means that array elements- stored in a single, continuous block of memory in a specific order. e.g books on shelf kept in it without any gaps continuously.

CONTIGUOUS: [1][2][3][4][5][6]  ← All elements in one continuous block
           
NON-CONTIGUOUS: [1][2][_][3][4][_][5][6]  ← Gaps! Not continuous


there are types of Contiguity: 

### 1. C-Contiguous(Row-major)

In [ ]:
# elements stored: row by row in memory
import numpy as np

# C-contiguous array (default in NumPy)
arr_c = np.array([[1, 2, 3],
                  [4, 5, 6]])

# In memory (C-order): [1, 2, 3, 4, 5, 6]
#                        row0     row1

print(f"C-contiguous? {arr_c.flags.c_contiguous}")  # True
print(f"F-contiguous? {arr_c.flags.f_contiguous}")  # False

### 2. F-Contiguity(Column-major)

In [ ]:
import numpy as np

# F-contiguous array
arr_f = np.array([[1, 2, 3],
                  [4, 5, 6]], order='F')

# In memory (F-order): [1, 4, 2, 5, 3, 6]
#                        col0 col1 col2

print(f"C-contiguous? {arr_f.flags.c_contiguous}")  # False
print(f"F-contiguous? {arr_f.flags.f_contiguous}")  # True

### Visually:

In [ ]:
import numpy as np

# Create a simple 2x3 array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Logical view (how we see it):")
print(arr)
print("\n" + "="*50)

print("Physical memory layout (C-contiguous):")
print("Memory addresses: [10]←→[20]←→[30]←→[40]←→[50]←→[60]")
print("                 └─row0──┘   └─row1──┘")
print("Elements are stored sequentially with no gaps")

### What Makes Arrays Non-Contiguous?

#### 1. Slicing with steps

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array (C-contiguous):")
print(arr)
print(f"C-contiguous? {arr.flags.c_contiguous}")  # True

# Take every other column
sliced = arr[:, ::2]
print("\nSliced array (every other column):")
print(sliced)
print(f"C-contiguous? {sliced.flags.c_contiguous}")  # False - not contiguous!

# Why? Because in memory, we're skipping elements:
# Original in memory: [1,2,3,4,5,6,7,8,9,10,11,12]
# Sliced accesses:    [1,  3,  5,  7,  9,  11] - jumping over elements

#### 2. Transposing

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:")
print(arr)
print(f"C-contiguous? {arr.flags.c_contiguous}")  # True

# Transpose the array
transposed = arr.T
print("\nTransposed:")
print(transposed)
print(f"C-contiguous? {transposed.flags.c_contiguous}")  # False
print(f"F-contiguous? {transposed.flags.f_contiguous}")  # True (now column-major)

### Why Contiguity Matters:

### 1. Performance Impact

In [54]:
import numpy as np
import time

# Create large arrays
size = 5000
contiguous_arr = np.random.rand(size, size)
non_contiguous = contiguous_arr[:, ::2]  # Skip columns - makes non-contiguous

print(f"Contiguous: {contiguous_arr.flags.c_contiguous}")
print(f"Non-contiguous: {non_contiguous.flags.c_contiguous}")

# Sum operation on contiguous array
start = time.time()
sum1 = np.sum(contiguous_arr)
time1 = time.time() - start

# Sum operation on non-contiguous array
start = time.time()
sum2 = np.sum(non_contiguous)
time2 = time.time() - start

print(f"\nContiguous sum time: {time1:.4f} seconds")
print(f"Non-contiguous sum time: {time2:.4f} seconds")
print(f"Non-contiguous is {time2/time1:.1f}x slower")

Contiguous: True
Non-contiguous: False

Contiguous sum time: 0.0459 seconds
Non-contiguous sum time: 0.0420 seconds
Non-contiguous is 0.9x slower


### 2. Effect on ravel() and reshape()

In [ ]:
import numpy as np

# Contiguous array - ravel returns view
contiguous = np.array([[1, 2, 3], [4, 5, 6]])
r1 = contiguous.ravel()
print(f"Contiguous ravel is view? {r1.base is contiguous}")  # True

# Non-contiguous array - ravel may return copy
non_contiguous = contiguous[:, ::2]  # Take every other column
r2 = non_contiguous.ravel()
print(f"Non-contiguous ravel is view? {r2.base is non_contiguous}")  # False (copy!)

### Checking and Converting Contiguity:
#### Check contiguity:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print("Contiguity flags:")
print(f"C-contiguous (row-major): {arr.flags.c_contiguous}")
print(f"F-contiguous (column-major): {arr.flags.f_contiguous}")
print(f"Contiguous overall: {arr.flags.contiguous}")

#### Make array contiguous:

In [ ]:
import numpy as np

# Create non-contiguous array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
non_contiguous = arr[:, ::2]  # Every other column
print("Original (non-contiguous):")
print(non_contiguous)
print(f"Is contiguous? {non_contiguous.flags.c_contiguous}")  # False

# Make it contiguous using copy()
contiguous_copy = non_contiguous.copy()
print("\nAfter copy() - now contiguous:")
print(contiguous_copy)
print(f"Is contiguous? {contiguous_copy.flags.c_contiguous}")  # True

# Or use np.ascontiguousarray()
contiguous_version = np.ascontiguousarray(non_contiguous)
print(f"\nascontiguousarray result: {contiguous_version.flags.c_contiguous}")  # True

# Difference between  flatten(), flat, and ravel()

## Memory and Performance Comparison:

In [56]:
import numpy as np
import time

# Create a large array
large_arr = np.random.rand(5000, 5000)

print("="*60)
print("PERFORMANCE COMPARISON")
print("="*60)

# 1. flatten() - creates copy (slowest, uses most memory)
start = time.time()
f = large_arr.flatten()
flatten_time = time.time() - start
print(f"flatten(): {flatten_time:.4f} seconds")
print(f"  - New array created: {f.flags.owndata}")
print(f"  - Memory: {f.nbytes / 1e6:.1f} MB additional")

# 2. ravel() - creates view (fastest, no extra memory)
start = time.time()
r = large_arr.ravel()
ravel_time = time.time() - start
print(f"\nravel(): {ravel_time:.4f} seconds")
print(f"  - Is view: {r.base is large_arr}")
print(f"  - Memory: 0 MB additional (shares data)")

# 3. flat - iterator (fast for iteration)
start = time.time()
total = sum(large_arr.flat)  # Iterate using flat
flat_time = time.time() - start
print(f"\nflat iteration: {flat_time:.4f} seconds")
print(f"  - No array created")

print(f"\nSpeed ratios:")
print(f"  flatten() is {ravel_time/flatten_time:.2f}x slower than ravel()")

PERFORMANCE COMPARISON
flatten(): 0.1825 seconds
  - New array created: True
  - Memory: 200.0 MB additional

ravel(): 0.0240 seconds
  - Is view: True
  - Memory: 0 MB additional (shares data)

flat iteration: 4.0242 seconds
  - No array created

Speed ratios:
  flatten() is 0.13x slower than ravel()


## When Copies vs Views Happen:

In [ ]:
import numpy as np

# Create arrays with different properties
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("="*60)
print("WHEN RAVEL() RETURNS VIEW VS COPY")
print("="*60)

# Case 1: Contiguous array - ravel returns VIEW
print(f"\n1. Contiguous array:")
print(f"   C-contiguous? {arr.flags.c_contiguous}")  # True
r1 = arr.ravel()
print(f"   ravel is view? {r1.base is arr}")  # True

# Case 2: After transpose - may return COPY
arr_t = arr.T
print(f"\n2. Transposed array:")
print(f"   C-contiguous? {arr_t.flags.c_contiguous}")  # False
r2 = arr_t.ravel()
print(f"   ravel is view? {r2.base is arr_t}")  # False (copy!)

# Case 3: Sliced array with step - returns COPY
arr_sliced = arr[:, ::2]  # Every other column
print(f"\n3. Sliced array (step=2):")
print(f"   C-contiguous? {arr_sliced.flags.c_contiguous}")  # False
r3 = arr_sliced.ravel()
print(f"   ravel is view? {r3.base is arr_sliced}")  # False (copy!)

## Practical Use Cases:
### When to use flatten():

In [ ]:
import numpy as np

# You need an independent copy for later modification
data = np.array([[1, 2, 3], [4, 5, 6]])

# Save original for later
original = data.copy()

# Work on flattened copy
flat_data = data.flatten()
flat_data = flat_data * 2  # Modify copy
flat_data = flat_data.reshape(2, 3)  # Reshape copy

print("flatten() use case - independent copy:")
print(f"Modified copy:\n{flat_data}")
print(f"Original unchanged:\n{data}")

### When to use flat:

In [ ]:
import numpy as np

# You need to iterate or assign values efficiently
matrix = np.zeros((3, 3))

# Set diagonal using flat indexing
matrix.flat[::4] = [1, 2, 3]  # 0, 4, 8 positions

# Or iterate through all elements
for i, val in enumerate(matrix.flat):
    if val == 0:
        matrix.flat[i] = -1

print("flat use case - efficient assignment:")
print(matrix)

### When to use ravel():

In [ ]:
import numpy as np

# Memory-efficient operations on large arrays
large_array = np.random.rand(1000, 1000)

# Get 1D view without copying
flat_view = large_array.ravel()

# Perform operations (modifies original!)
flat_view = flat_view * 2  # Doubles all values
flat_view = np.sqrt(flat_view)  # Square root

print("ravel() use case - memory efficient:")
print(f"Original array modified: {large_array[0, :5]}")
print(f"View shares data: {flat_view.base is large_array}")

# Transpose()

- it interchanges the columns and rows  or say reverses the axes.
- it returns the view and no new array is created.
- syntax:np.transpose(arr,axis=None) or arr.transpose(axis=None) or arr.T

## 2D-array

In [25]:
import numpy as np
arr_2d=np.arange(1,10).reshape(3,3)
print(f"arr: {arr_2d}")
print("-"*50)

# transposing
transposed=arr_2d.T
print(f"transposed: {transposed}")
print(f"arr_2d is: {arr_2d}")
print("-"*50)

# Transposing a 1D array dosent change!
arr_1d=np.arange(1,10)
arr_transposed=arr_1d.T
print(f"original 1d: {arr_1d}")
print(f"transposed 1d: {arr_transposed}")
print("Both are same!!")

# To do so, we use reshape
col_arr_1d=arr_1d.reshape(-1,1)
print(f"column array of arr_1d: {col_arr_1d}")
row_arr_1d=arr_1d.reshape(1,-1)
print(f"row array of arr_1d: {row_arr_1d}")
print("-"*50)

# 3D array transpose
arr_3d=np.arange(9).reshape(1,3,3)
print(f"arr_3d: {arr_3d}")
print(f"shape of arr_3d initially: {arr_3d.shape}")
arr_3d_trans=arr_3d.T
print(f"transposed arr_3d: {arr_3d_trans}")
print(f"shape of transposed arr_3d: {arr_3d_trans.shape}")
print("-"*50)

# transposing with specific axis permutation
arr=np.arange(24).reshape(2,3,4)
print(arr)
print("-"*50)

print(f"original shape: {arr.shape}")
t1=arr.transpose() # default transpose
print(f"shape of t1: {t1.shape}")
print("-"*50)

# by specifying ordrer- keeping first axis same and swapping last two axis
# print(help(np.transpose))
t2=arr.transpose(0,2,1)
print(f"t2: {t2}")
print(f"shape of t2: {t2.shape}")
print("-"*50)

# moving axes 2 to front
t3=arr.transpose(2,0,1)
print(f"t3: {t3}")
print(f"shape of t3: {t3.shape}")

arr: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
transposed: [[1 4 7]
 [2 5 8]
 [3 6 9]]
arr_2d is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
original 1d: [1 2 3 4 5 6 7 8 9]
transposed 1d: [1 2 3 4 5 6 7 8 9]
Both are same!!
column array of arr_1d: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
row array of arr_1d: [[1 2 3 4 5 6 7 8 9]]
--------------------------------------------------
arr_3d: [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
shape of arr_3d initially: (1, 3, 3)
transposed arr_3d: [[[0]
  [3]
  [6]]

 [[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]]
shape of transposed arr_3d: (3, 3, 1)
--------------------------------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------
original shape: (2, 3, 4)
shape of t1: (4, 3, 2)
--------------------------------------------------
t2: [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]

## Visual representation of axis permutation:

In [30]:
import numpy as np
arr=np.array([[[1,2,3],
               [4,5,6]],
              
              [[7,8,9],
               [10,11,12]]])   # arr shape: (2,2,3)
print(f"arr: {arr}")
print(f"arr shape: {arr.shape}")
print("-"*50)

# Transposing with different axis orders
t1=arr.transpose(1,0,2)
print(f"t1 shape: {t1.shape}")
print(f"t1: {t1}")
print("-"*50)

#other transpose
t3=arr.transpose(2,0,1)
print(f"shape of t2: {t2.shape}")
print(f"t2: {t2}")

arr: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr shape: (2, 2, 3)
--------------------------------------------------
t1 shape: (2, 2, 3)
t1: [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
--------------------------------------------------
shape of t2: (2, 4, 3)
t2: [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


## Common Applications: 

### 1. Matrix Multiplication Requirements

In [ ]:
import numpy as np

# In matrix multiplication, inner dimensions must match
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # Shape: (2, 3)

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])  # Shape: (3, 2)

# These work directly
C = np.dot(A, B)  # (2,3) @ (3,2) → (2,2)

# If dimensions don't match, transpose can help
B_wrong = np.array([[7, 8, 9],
                    [10, 11, 12]])  # Shape: (2, 3)

# This would error: np.dot(A, B_wrong)  # (2,3) @ (2,3) won't work
# Fix by transposing
result = np.dot(A, B_wrong.T)  # (2,3) @ (3,2) works!
print(f"After transpose: {result.shape}")  # (2, 2)

### 2. Image Processing

In [ ]:
import numpy as np

# RGB image: (height, width, channels)
image = np.random.randint(0, 255, (100, 200, 3))
print(f"Original image shape: {image.shape}")  # (100, 200, 3)

# Transpose to (channels, height, width) for some ML libraries
image_t = image.transpose(2, 0, 1)
print(f"After transpose: {image_t.shape}")  # (3, 100, 200)

# Or to (width, height, channels)
image_t2 = image.transpose(1, 0, 2)
print(f"Width-first shape: {image_t2.shape}")  # (200, 100, 3)

### 3. Computing Dot Products

In [ ]:
import numpy as np

# Calculate similarity between vectors
vectors = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])  # Shape: (3, 3)

# Compute cosine similarity matrix
# Using transpose to broadcast correctly
similarity = np.dot(vectors, vectors.T)
print("Similarity matrix:")
print(similarity)

### Transpose vs Reshape:

In [ ]:
import numpy as np

arr = np.arange(6).reshape(2, 3)
print("Original array:")
print(arr)
# [[0 1 2]
#  [3 4 5]]

# Transpose - rearranges data
transposed = arr.T
print("\nTranspose (rearranges data):")
print(transposed)
# [[0 3]
#  [1 4]
#  [2 5]]

# Reshape - just changes view without rearranging
reshaped = arr.reshape(3, 2)
print("\nReshape (just changes shape):")
print(reshaped)
# [[0 1]
#  [2 3]
#  [4 5]]  - Different result!

### Memory and Performance:

In [ ]:
import numpy as np

# Transpose creates a VIEW, not a copy
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

t_arr = arr.T
print(f"Original array:\n{arr}")
print(f"Transposed:\n{t_arr}")

# Prove it's a view
t_arr[0, 0] = 99
print(f"\nAfter modifying transpose:")
print(f"Transposed:\n{t_arr}")
print(f"Original:\n{arr}")  # Original changed!

# Check contiguity
print(f"\nOriginal C-contiguous? {arr.flags.c_contiguous}")  # True
print(f"Transpose C-contiguous? {t_arr.flags.c_contiguous}")  # False
print(f"Transpose F-contiguous? {t_arr.flags.f_contiguous}")  # True

##### Doubt question:
what is axes ? 
what reps the numbers in arr.transpose(2,0,1)   
are axes like indexes for the shape dimensions?

answer -
Axes are indeed the indexes (positions) of the dimensions in an array's shape. Think of them as the "coordinates system" for your array.
###### Understanding Axes:

In [ ]:
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2],
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]],
                
                [[9, 10],
                 [11, 12]]])

print(f"Array shape: {arr.shape}")  # (3, 2, 2)

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]]])

# To access element 7: arr[axis0, axis1, axis2]
print(arr[1, 1, 0])  # 7
#       │   │   │
#       │   │   └── Axis 2 (column 0)
#       │   └────── Axis 1 (row 1)
#       └────────── Axis 0 (matrix 1)

# To access element 10: arr[axis0, axis1, axis2]
print(arr[2, 0, 1])  # 10
#       │   │   │
#       │   │   └── Axis 2 (column 1)
#       │   └────── Axis 1 (row 0)
#       └────────── Axis 0 (matrix 2)
# **an axis is denoted by the '[' bracket in-
# arrray([[[1,2,3],
#         [4,5,6]],
#        
#        [[7,8,9],
#         [10,11,12]]])

# Multiple arrays joining into a single array-

## 1. concatenate()-
syntax: 

np.concatenate((arr1,arr2,...), axis=0, out=None, dtype=None, casting="same_kind")

while concatenating the axis determines how the arrays will be joined together. 
- axis=0 : vertical concatenation performed
- axis=1 : horizontal concatenation
- axis=None : first arrays will be converted to 1D array and then will be performing concatenation on the resultant arrays
- any number of arrays can be joined, but they must all have the same dimension
- all axes sizes, except the concatenation axis, should be the same
- the shapes of the output array and the resultant array must match.

In [22]:
import numpy as np
arr1= np.arange(4)
arr2= np.arange(5)
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print("-"*50)

arr1: [0 1 2 3]
arr2: [0 1 2 3 4]
--------------------------------------------------


In [23]:
## Concatenation

In [24]:
concatenated=np.concatenate((arr1,arr2))
print(f"concatenated: {concatenated}")
print("-"*50)

concatenated: [0 1 2 3 0 1 2 3 4]
--------------------------------------------------


In [25]:
## 2D-arrays

In [26]:
arr2d_1=np.arange(4).reshape(2,2)
arr2d_2=np.arange(5,9).reshape(2,2)
print("arr2d_1 : ")
print(f"{arr2d_1}")
print("arr2d_2 :")
print(f"{arr2d_2}")
print("-"*50)

arr2d_1 : 
[[0 1]
 [2 3]]
arr2d_2 :
[[5 6]
 [7 8]]
--------------------------------------------------


In [27]:
### with axes:

In [28]:
con1=np.concatenate((arr2d_1,arr2d_2),axis=0)
print("axis=0 concatenation:")
print(f" {con1}")
con2=np.concatenate((arr2d_1,arr2d_2),axis=1)
print("axis=1 concatenation:")
print(f" {con2}")
con3=np.concatenate((arr2d_1,arr2d_2),axis=None)
print("axis= None concatenation:")
print(f" {con2}")
# * when axis=None, it flattens both the arrays first and then concatenates thats why the result is a 1D-array

axis=0 concatenation:
 [[0 1]
 [2 3]
 [5 6]
 [7 8]]
axis=1 concatenation:
 [[0 1 5 6]
 [2 3 7 8]]
axis= None concatenation:
 [[0 1 5 6]
 [2 3 7 8]]


In [29]:
### out parameter and dtype usage
### after concatenation using the out parameter, we can store array in a new location , but out and result must have same shape

In [37]:
arr3=np.arange(5)
arr4=np.arange(3)
empty_int=np.empty(8,dtype=int)
result = np.concatenate((arr3, arr4), out=empty_int)
print(f"out with matching dtype: {result}")
print(f"empty_int now: {empty_int}")  # Same as result

# To use dtype parameter:
result2 = np.concatenate((arr3, arr4), dtype=float)  # Convert to float
print(f"\nWith dtype=float: {result2}")
print(f"dtype: {result2.dtype}")  # float64

# print(f"out and dtype usage: {np.concatenate((arr3,arr4), out=empty, dtype=str)}")   # this gives error

out with matching dtype: [0 1 2 3 4 0 1 2]
empty_int now: [0 1 2 3 4 0 1 2]

With dtype=float: [0. 1. 2. 3. 4. 0. 1. 2.]
dtype: float64


## Casting Parameter:
controls what kind of conversion are allowed

In [ ]:
import numpy as np
arr1=np.array([1,2,3],dtype=int)
arr2=np.array([1.5,2.5,3.5],dtype=float)

#Different casting rules:
try:
    # 'no' casting- no conversion allowed
    r1=np.concatenate((a,b),casting='no')
except TypeError as e:
    print(f"'no' casting error: {e}")

# 'equiv' - only identical types
try:
    r2= np.concatenate((a,b), casting='equiv')
except TypeErroe as e:
    print(f"'equiv' casting error: {e}")

#'safe' - no data loss
try:
    r3=np.concatenate((a,b),casting='safe')
except TypeError as e:
    print(f"'safe' casting error: {e}")

# same_kind'- allows safe casts and some unsafe(default)
r4=np.concatenate((a,b), casting='same_kind')
print(f"'same_kind' result: {r4}")

# 'unsafe' - any conversion allowed
r5=np.concatenate((a,b), casting='unsafe')
print(f"'unsafe' result: {r5}")

In [ ]:
## Complete Example with All Parameters:
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([4.5, 5.5, 6.5], dtype=np.float64)

# Pre-allocate output array
output = np.empty(6, dtype=np.float64)

# Concatenate with all parameters
result = np.concatenate(
    (arr1, arr2), 
    axis=0, 
    out=output, 
    dtype=np.float64, 
    casting='safe'
)

print(f"Result: {result}")
print(f"Output array: {output}")
print(f"Result dtype: {result.dtype}")

### Casting is converting data from one type to another (e.g., integer → float).

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)      # integers
b = np.array([4.5, 5.5, 6.5], dtype=float)  # floats

# 1. 'no' - NO conversion allowed (must be exact same type)
# np.concatenate((a, b), casting='no')  # ERROR! int vs float

# 2. 'equiv' - ONLY identical types allowed
# np.concatenate((a, b), casting='equiv')  # ERROR! int vs float

# 3. 'safe' - ONLY conversions that preserve value
# np.concatenate((a, b), casting='safe')  # ERROR! float → int loses .5

# 4. 'same_kind' - allows between similar types (DEFAULT)
r1 = np.concatenate((a, b), casting='same_kind')
print(f"same_kind: {r1}")  # Works: int ↔ float

# 5. 'unsafe' - ANY conversion allowed
r2 = np.concatenate((a, b), casting='unsafe')
print(f"unsafe: {r2}")  # Works, anything goes

## stack()

- joins arrays- along new axis
- concatenate- joins along existing axis
- creates an additional dimension
- Syntax: np.stack((array1, array2, array3), axis=0)

In [39]:
# difference between concatenate and stack
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# concatenate() - joins along EXISTING axis
c_concat = np.concatenate((a, b))
print(f"concatenate: {c_concat}")  # [1 2 3 4 5 6]
print(f"Shape: {c_concat.shape}")  # (6,) - still 1D

# stack() - creates NEW axis
c_stack = np.stack((a, b))
print(f"\nstack: \n{c_stack}")
print(f"Shape: {c_stack.shape}")  # (2, 3) - now 2D!
# [[1 2 3]
#  [4 5 6]]

concatenate: [1 2 3 4 5 6]
Shape: (6,)

stack: 
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### Visual Understanding:

### axis parameters: 
- determines where the new dimension is inserted in the shape tuple

## vsatack()

- stacks arrays vertically
- input as the sequence and output is the single vertically stacked array.
- equivalent to concatenation along the first (axis=0) axis, following the reshaping of 1D-arrays of shape-(N,) to -(1,N).
- ALL INPUT ARRAYS MUST HAVE - SAME SHAPE EXCEPT AT AXIS 0.
- Syntax: np.vstack(tup, * , dtype=None, casting='same_kind').

In [2]:
import numpy as np
#1D-array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print("-"*50)

#vstack()
result=np.vstack([arr1,arr2])
print(f"vstacked: {result}")
print(f"shape: {result.shape}")
print("-"*50)

arr1: [1 2 3]
arr2: [4 5 6]
--------------------------------------------------
vstacked: [[1 2 3]
 [4 5 6]]
shape: (2, 3)


Key Differences from stack()

In [3]:
# Compare vstack vs stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("vstack([a, b]):")
print(np.vstack([a, b]))
print("Shape:", np.vstack([a, b]).shape)
print()

print("stack([a, b], axis=0):")
print(np.stack([a, b], axis=0))
print("Shape:", np.stack([a, b], axis=0).shape)

# For 1D arrays, they look similar but:
# - vstack: adds a new dimension only if needed
# - stack: ALWAYS adds a new dimension

vstack([a, b]):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

stack([a, b], axis=0):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## hstack()

- inputs as arrays sequence and returns a single horizontally stacked array.
- important- all along the input arrays must have the same dimensions.
- equivalent to concatenation along 2nd axis, except for 1Darrays, where it concatenates along the first axis.
- Syntax: np.hstack(tup, *, dtype=None, casting='same_kind')

In [11]:
import numpy as np
#1D-array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")
print()

# hstack: 
result=np.hstack([arr1,arr2])
print(f"result: {result}")
print(f"shape: {result.shape}")
print()

arr1 :[1 2 3]
arr2 :[4 5 6]

result: [1 2 3 4 5 6]
shape: (6,)



In [12]:
#for 2D-arrays
arr1=np.arange(4).reshape(2,2)
arr2=np.arange(4,8).reshape(2,2)
print("arr1:")
print(arr1)
print(arr1.shape)
print("\narr2:")
print(arr2)
print(arr2.shape)
print()

#hstack them:
result=np.hstack([arr1,arr2])
print("\nAfter hstack:")
print(result)
print(f"Shape: {result.shape}")

arr1:
[[0 1]
 [2 3]]
(2, 2)

arr2:
[[4 5]
 [6 7]]
(2, 2)


After hstack:
[[0 1 4 5]
 [2 3 6 7]]
Shape: (2, 4)


## dstack()
stands for depth stack. stacks arrays in sequence depth-wise (along third axis), which is equivalent to concatenation along the third axis

- stacks arrays along axis two, which is the third axis
- input-arrays sequence returns- a single array returned by stacking them along third axis.
- 1D-arrays or 2D-arrays must have same shape.
- equivalent to concatenation of 2D arrays of shape (A,B) and (A,B,1) and 1D-arrays of shape (A,) into (1,A,1) along the third axis.
- Syntax: np.dstack(tup)

In [1]:
import numpy as np

# 2D-array
arr1=np.array([[1,2],
              [3,4]])
arr2=np.array([[5,6],
              [7,8]])
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print()

# dstacking them:
result=np.dstack([arr1,arr2])
print("\nAfter dstack:")
print(result)
print(f"Shape: {result.shape}")

arr1:
[[1 2]
 [3 4]]

arr2:
[[5 6]
 [7 8]]


After dstack:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape: (2, 2, 2)


## dstack vs Other Stacking Functions

In [ ]:
# Create sample data
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

c = np.array([[13, 14, 15],
              [16, 17, 18]])

print("Original array a (2x3):")
print(a)
print("\nOriginal array b (2x3):")
print(b)

# dstack - depth stacking (along axis=2)
print("\ndstack([a, b]):")
dstack_result = np.dstack([a, b])
print(dstack_result)
print("Shape:", dstack_result.shape)

# vstack - vertical stacking (along axis=0)
print("\nvstack([a, b]):")
vstack_result = np.vstack([a, b])
print(vstack_result)
print("Shape:", vstack_result.shape)

# hstack - horizontal stacking (along axis=1)
print("\nhstack([a, b]):")
hstack_result = np.hstack([a, b])
print(hstack_result)
print("Shape:", hstack_result.shape)

# stack with axis=2
print("\nstack([a, b], axis=2):")
stack_result = np.stack([a, b], axis=2)
print(stack_result)
print("Shape:", stack_result.shape)

## Comparison Table

## so in dstack, is the layer 2 behind the layer 1?

In [ ]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.dstack([arr1, arr2])
print(result)
print(f"Shape: {result.shape}")

### Indexing Demonstration

In [ ]:
# Let's see how to access each layer
result = np.dstack([arr1, arr2])

# Access the BOTTOM layer (first array - arr1)
bottom_layer = result[:, :, 0]
print("Bottom layer (index 0):")
print(bottom_layer)
# Output:
# [[1 2]
#  [3 4]]

# Access the TOP layer (second array - arr2)
top_layer = result[:, :, 1]
print("\nTop layer (index 1):")
print(top_layer)
# Output:
# [[5 6]
#  [7 8]]

# Splitting of arrays in numpy

## 1. split()
splits array into multiple sub-arrays of equal size along a specified axis and returns ndarray object list.
- if array splitin gis based on sections , then sub arrays size should be equal. or else - error
- Syntax: np.split(arr, indices_or_sections, axis=0)

In [2]:
import numpy as np
arr1=np.arange(1,7)
arr2=np.split(arr1,3)
print(f"array type is: {type(arr2)}")
print(f"subarrays are: {arr2}")

array type is: <class 'list'>
subarrays are: [array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
arr3= np.arange(1,19).reshape(6,3)
print(arr3)
print("array split into 2 sections:")
print(f"{np.split(arr3,2,axis=0)}")
print("-"*50)
print()

# along axis=1
arr3= np.arange(1,25).reshape(6,4)
print(arr3)
print("array split into 2 sections along axis = 1:")
print(f"{np.split(arr3,2,axis=1)}")
print("-"*50)
print()

#array split into 6 sections:
print(f"array split into 6 sections: {np.split(arr3,6,axis=0)}")
print("-"*50)
print()

# splitting 1D-arrays based on indices
arr4=np.arange(1,11)
result=np.split(arr4,[3,6])
print("arr4 split in sections based on indice - [3,6]")
print(f"{result}")
print("-"*50)
print()

# Splitting 2D-arrays based on indices
arr5=np.arange(1,19).reshape(3,6)
print("arr5: ")
print(arr5)
result=np.split(arr5,[3,5],axis=1)
print("result for 2D array split by indices: ")
print(f"{result}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
array split into 2 sections:
[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]
--------------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
array split into 2 sections along axis = 1:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
--------------------------------------------------

array split into 6 sections: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]
--------------------------------------------------

arr4 split in sections based on indice - [3,6]
[array([1, 2, 3]), array([4, 5, 6]), array([ 

## 2. vsplit()
- Allows row-wise splitting of array into multiple sub-arrays vertically along axis=0.
- input array must be 2D-array as 1D-array cannot be split vertically.
- Syntax: np.vsplit(arr,indices_or_sections)

In [24]:
import numpy as np
arr1=np.arange(1,17).reshape(4,4)
print(arr1)
print("-"*50)
print()

# Spilitting based on sections
print(f"vsplit:2 {np.vsplit(arr1,2)}")
print("-"*50)
print()

# splitting into 4
print(f"vsplit:4 {np.vsplit(arr1,4)}")
print("-"*50)
print()

# splitting by indices-
print(f"vsplit by indices:2 {np.vsplit(arr1,[2,3])}")
print("-"*50)
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------------------

vsplit:2 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
--------------------------------------------------

vsplit:4 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]
--------------------------------------------------

vsplit by indices:2 [array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]
--------------------------------------------------



## 3. hsplit()
- allows column wise splitting of array into multiple sub-arrays horizontally. along axis=1.
- Syntax: np.split(arr,indices_or_sections)

In [3]:
import numpy as np
arr1=np.arange(1,9).reshape(2,4)
print("arr1")
print(arr1)
print("-"*50)
print()

# splitting by sections into 2
print("by sections in 2 sections :")
print(np.hsplit(arr1,2))
print("-"*50)
print()

# splitting by sections into 4
print("by sections in 4 sections :")
print(np.hsplit(arr1,4))
print("-"*50)
print()

# based on indces
print("by indices :")
print(np.hsplit(arr1,[1,3]))
print("-"*50)
print()

arr1
[[1 2 3 4]
 [5 6 7 8]]
--------------------------------------------------

by sections in 2 sections :
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
--------------------------------------------------

by sections in 4 sections :
[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]
--------------------------------------------------

by indices :
[array([[1],
       [5]]), array([[2, 3],
       [6, 7]]), array([[4],
       [8]])]
--------------------------------------------------



## 4. dsplit()
- allows thirs dimension splitting of an array into multiple subarrays along axis=2, which means depth split.
- Syntax: np.dsplit(arr,indices_or_sections)

In [7]:
import numpy as np
arr1=np.arange(24).reshape(2,3,4)
print("arr1 :")
print(arr1)
print("-"*50)
print()

# splitting by sections
print("splitting by sections")
print(np.dsplit(arr1,2))
print("-"*50)
print()

# splitting by indices
print("splitting by indices")
print(np.dsplit(arr1,[1,3]))
print("-"*50)
print()

arr1 :
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------

splitting by sections
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
--------------------------------------------------

splitting by indices
[array([[[ 0],
        [ 4],
        [ 8]],

       [[12],
        [16],
        [20]]]), array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[13, 14],
        [17, 18],
        [21, 22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]
--------------------------------------------------



## array_split()
- aloows to have unequal splitting of array into sub-arrays if the split number does not divide the given axis evenly.
- returns=a%n subarrays , size=(a//n)+1 and the rest of size a//n for an array of length a that should be divided into n parts.
- Syntax: np.array_split(arr,indices_or_Sections,axis=0)

In [15]:
import numpy as np
arr1=np.arange(10)
print("1D-array")
print(arr1)
split_arr=np.array_split(arr1,3)

# --------------------------------------------
# 10%3=1 subarray having size as 10//3 +1 = 4
# and rest 2 subarray of each size 10//3=3

# Concept: # a % n sub-arrays of size a//n + 1 
# where a: length and n sections

# and the rest of size a//n
# --------------------------------------------

print("array split 1D: ")
print(split_arr)  # Q: how to know which array will be unequal.. 1st, 2nd, 3rd or what ??

1D-array
[0 1 2 3 4 5 6 7 8 9]
array split 1D: 
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [16]:
arr2 = np.arange(10).reshape(5,2)
print("arr2")
print(arr2)
print("="*50)
print()
arr2_split=np.array_split(arr2,4)

#---------------------------------------------------
# Concept: # 5 % 4 (1) sub-arrays of size 5//4 + 1 = 2
# and the rest (3) subarrays of size 5//4 = 1
#---------------------------------------------------

print("Splitting 2D-array by array_split:")
print(arr2_split)

arr2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Splitting 2D-array by array_split:
[array([[0, 1],
       [2, 3]]), array([[4, 5]]), array([[6, 7]]), array([[8, 9]])]


# Sorting of ndarray in numpy

using sort()
- sorts elements around a specified axis in an array
- default sorting algorith- quicksort and sorting happens in ascending order
- for 2D-arrays sorting happens based on columns by default, where every 1D-array will be sorted.
- Syntax: np.sort(arr, axis=-1, kind=None, order=None)

In [24]:
import numpy as np

# creating 1-D array in ascending order.
arr=np.array([45,34,68,34,67,26,9,98,35])
print("arr")
print(arr)
print("-"*50)
print()

# sorting
print(f"sorted arr: {np.sort(arr)}")
print("-"*50)
print()

# sorting in descending order
print(f"sorted arr in descending order: {-np.sort(-arr)}")
print("-"*50)
print()

# String sorted 1D-array in ascending order- 
arr2 =np.array(['mat','hat','rat','bat','cat'])
print(f"String sorted 1-D array in ascending order is {np.sort(arr2)}") # default sorting is ascending

print(f"String sorted 1-D array in descending order is {np.sort(arr2)[::-1]}")
print('-'*50)

arr
[45 34 68 34 67 26  9 98 35]
--------------------------------------------------

sorted arr: [ 9 26 34 34 35 45 67 68 98]
--------------------------------------------------

sorted arr in descending order: [98 68 67 45 35 34 34 26  9]
--------------------------------------------------

String sorted 1-D array in ascending order is ['bat' 'cat' 'hat' 'mat' 'rat']
String sorted 1-D array in descending order is ['rat' 'mat' 'hat' 'cat' 'bat']
--------------------------------------------------


In [3]:
# 2D-array
import numpy as np

arr3= np.array(([[78,35,98],[21,11,9],[87,35,65]]))
print("arr3: ")
print(arr3)
print("-"*50)
print()

# sorting 2D-array in ascensing order:
print(f"Sorted arr3 (2D-array) in ascending order is : {np.sort(arr3)}")
print(f"Sorted arr3 (2D-array) in descending order is {np.sort(-arr3)}")
print("-"*50)
print()
 
print("Sorting based on same marks of Students and correct questions attempted in ascendong order")
print()
data = [('name', object), ('marks', float), ('correct_questions', int)]
values = [('Saurabh', 89.5, 52), ('Pallavi', 67, 38),('Priyanka', 89.5, 53),('Yathartha', 88, 51)]
datatype = np.array(values, dtype=data)
sort_marks_correct = np.sort(datatype, order=['marks', 'correct_questions'])
print()
print(f"Original Array is :\n {data}")
print()
print(f"Sorting carried out based on correct_questions :\n {sort_marks_correct}")

arr3: 
[[78 35 98]
 [21 11  9]
 [87 35 65]]
--------------------------------------------------

Sorted arr3 (2D-array) in ascending order is : [[35 78 98]
 [ 9 11 21]
 [35 65 87]]
Sorted arr3 (2D-array) in descending order is [[-98 -78 -35]
 [-21 -11  -9]
 [-87 -65 -35]]
--------------------------------------------------

Sorting based on same marks of Students and correct questions attempted in ascendong order


Original Array is :
 [('name', <class 'object'>), ('marks', <class 'float'>), ('correct_questions', <class 'int'>)]

Sorting carried out based on correct_questions :
 [('Pallavi', 67. , 38) ('Yathartha', 88. , 51) ('Saurabh', 89.5, 52)
 ('Priyanka', 89.5, 53)]


# Elements searching of ndarray in numpy
- efficient querying and retrieval of specific elements or subsets of data within large arrays, enabling tasks such as data filtering, indexing, and conditional operations.
- used in scientific computing, data analysis, and machine learning.
- enhances versitality and usability of numpy arrays in diverse computational tasks, enabling efficient data manipulation and analysis.
- 2 methods:
   - where()
   - condition based selection

## 1. where()-
- the indics of the elements that satisfy the criterion will be returned if we simply point out the conditon.
- does not return elements.
- if provided are - condition, x,y then : the places which meet condition are replaced by x and y
- returns indices and will serve as a replacement operator as well.
- when used as a replacement operator, the functioning is like that of a ternatry operator
- Syntax: np.where(condition,[x,y],/)

In [ ]:
import numpy as np
print(help(np.where))

In [15]:
import numpy as np
arr1 = np.arange(1,6)
print("arr")
print(arr)
result1=np.where(arr<3,arr,0) # where arr < 3 it returns value of arr normally but where not, it returns 0 in that place
print(result1)
print(f"is result same as arr: {result1 is arr}") # that means it is an object
print("-"*50)
print()

# Different values for True/False
arr2 = np.array([10, 20, 30, 40, 50])
result2 = np.where(arr2>25,"High", "Low")  # where conition met : high and where not: low
print(result2)

# replacing based on condition
arr3= np.array([1, 2, 3, 4, 5])
x=np.array([100,200,300,400,500])
y=np.array([0,0,0,0,0])
result=np.where(arr3>3,x,y)
print(result)

arr
[1 2 3 4 5]
[1 2 0 0 0]
is result same as arr: False
--------------------------------------------------

['Low' 'Low' 'High' 'High' 'High']
[  0   0   0 400 500]


In [5]:
# real world example:
import numpy as np

# Student scores
scores=np.array([85, 42, 78, 95, 33, 67])
grades=np.where(scores>=60,"pass","fail")
print(f"Grades: {grades}")
print("-"*50)
print()

# With percentage calculation
marks = np.array([45, 78, 92, 38, 81])
adjusted_marks = np.where(marks < 40, marks * 1.1, marks)
print("After grace marks:", adjusted_marks)
# Output: [45.  78.  92.  41.8 81. ]  # 38 got 10% grace
print("-"*50)
print()

# Nested condition
arr=np.array([15, 25, 35, 45, 55])
result=np.where(arr<20,"Low",
       np.where(arr<40,"Medium","High"))
print(result)
print("-"*50)
print()

# Using logical operators
arr=np.array([10,25,30,45,50])
result=np.where((arr>=20)&(arr<=40),"In Range","Out of Range")
print(result)
print("-"*50)
print()

Grades: ['pass' 'fail' 'pass' 'pass' 'fail' 'pass']
--------------------------------------------------

After grace marks: [45.  78.  92.  41.8 81. ]
--------------------------------------------------

['Low' 'Medium' 'Medium' 'High' 'High']
--------------------------------------------------

['Out of Range' 'In Range' 'In Range' 'Out of Range' 'Out of Range']
--------------------------------------------------



### where without c and y (find indices)

In [ ]:
# Find indices where condition is True
arr = np.array([1, 2, 3, 2, 4, 2, 5])
indices = np.where(arr == 2)
print(indices)  # (array([1, 3, 5]),) - tuple of indices
print(indices[0])  # [1 3 5] - actual indices
print("-"*50)
print()

# 2D-array
arr_2d=np.arange(1,10).reshape(3,3)
print(f"arr_2d: {arr_2d}")
indices=np.where(arr_2d>5)
print(f"indices where >5: {indices}")
print(f"Values: {arr_2d[indices]}")   # used those indices to access elements

In [21]:
# student data analysis
# Using with structured arrays
import numpy as np
from numpy.lib import recfunctions
students=np.array([
    ('Saurabh',89.5,52),
    ('Pallavi',67.0,38),
    ('Priyanka',89.5,53),
    ('Yathartha',88.0,51)
],dtype=[('name','U10'),('marks',float),('correct',int)])

# finding high achievers-
high_achievers=np.where(students['marks']>85)
print("High achiever indices:",high_achievers)
print(f"High achievers: {students[high_achievers]}")
print("-"*50)
print()

# grades assignment-
grades=np.where(students['marks']>=85,'A',
               np.where(students['marks']>=70,'B','C'))
students_new=recfunctions.append_fields(
    students,
    'grade',
    grades,
    dtypes='U10',
    usemask=False
)                     # adds new column called grades
print(students_new)

High achiever indices: (array([0, 2, 3]),)
High achievers: [('Saurabh', 89.5, 52) ('Priyanka', 89.5, 53) ('Yathartha', 88. , 51)]
--------------------------------------------------

[('Saurabh', 89.5, 52, 'A') ('Pallavi', 67. , 38, 'C')
 ('Priyanka', 89.5, 53, 'A') ('Yathartha', 88. , 51, 'A')]


#### Advanced patterns-
using where() for array manipulation


In [31]:
import numpy as np

# replacing selected elements-
arr=np.arange(10)
arr=np.where((arr%2==0),arr*10,arr)
print(f"arr:{arr}")

# clipping values between min and max-
arr=np.array([1,4,10,15,20,25])
min_val,max_val=5,20
clipped=np.where(arr<min_val,min_val,
        np.where(arr>max_val,max_val,arr))
print(f"clipped: {clipped}")


# Find and replace outliers
data = np.array([10, 12, 15, 100, 13, 14, 200, 11])
mean = np.mean(data)
std = np.std(data)
outliers = np.where(np.abs(data - mean) > 2 * std)
print("Outlier indices:", outliers[0])
print("Outlier values:", data[outliers])

# Replace outliers with mean
cleaned = np.where(np.abs(data - mean) > 2 * std, mean, data)
print("Cleaned:", cleaned)

arr:[ 0  1 20  3 40  5 60  7 80  9]
clipped: [ 5  5 10 15 20 20]


### Common Mistakes to Avoid

In [ ]:
# Mistake 1: Using 'and' instead of '&'
arr = np.array([1, 2, 3, 4, 5])
# Wrong: np.where(arr > 2 and arr < 5, arr, 0)  # Error!
# Correct:
result = np.where((arr > 2) & (arr < 5), arr, 0)
print(result)  # [0 0 3 4 0]

# Mistake 2: Forgetting parentheses for conditions
# Wrong: np.where(arr > 2 & arr < 5)  # Wrong operator precedence
# Correct: np.where((arr > 2) & (arr < 5))

# Mistake 3: Using where() when boolean indexing is simpler
arr = np.array([1, 2, 3, 4, 5])
# Instead of: indices = np.where(arr > 3)[0]
# Simpler: indices = arr[arr > 3]

# Inserting elements into ndarray

- crucial for dynamic modification of array data.
- enables flexibility in aray manipulation and data processing tasks.
- where new data needs to be added to an existing array or modifying based on certain conditions.

# insert()-
- Syntax: np.insert(arr,obj,values,axis=None)
- arr= is input array
- obj= is index/position before which to insert(int,slice,or list of indices)
- values= Value(s) to insert (can be scalar or array-like)
- axis= axis along which to insert(None=flatten array first)

### with 1D-arrays: 

In [41]:
# basic usage in 1D-array
# insert single value
import numpy as np

# insert at a specific position
arr=np.array([1,2,3,4,5])
result=np.insert(arr,2,99) # inserts 99 before index=2
print(f"result: {result}")
print("-"*50)
print()

# insert at beginning
result=np.insert(arr,0,99)
print(f"result: {result}") 
print("-"*50)
print()

# insert at the end (using len(arr))
result=np.insert(arr, len(arr),99)
print(f"result: {result}")

result: [ 1  2 99  3  4  5]
--------------------------------------------------

result: [99  1  2  3  4  5]
--------------------------------------------------

result: [ 1  2  3  4  5 99]


In [42]:
# inserting multiple values
arr=np.array([1,2,3,4,5])

# insert multiple values at one position
result=np.insert(arr,2,[99,100,101])
print(f"result: {result}")
print("-"*50)
print()

# inserting at multiple positions
result=np.insert(arr,[1,3],[99,100])
print(result)
# 99 inserted before index 1, 100 inserted before index 3

result: [  1   2  99 100 101   3   4   5]
--------------------------------------------------

[  1  99   2   3 100   4   5]


In [43]:
# inserting same value at multiple positions
arr=np.array([1,2,3,4,5])
print(f"arr: {arr}")

# insert 0 at positions 0,2, and 4
result=np.insert(arr,[0,2,4],0)
print(f"result: {result}")
print("-"*50)
print()

# using slice
result=np.insert(arr,slice(1,4),99)
print(f"result: {result}")
print("-"*50)
print()



arr: [1 2 3 4 5]
result: [0 1 2 0 3 4 0 5]
--------------------------------------------------

result: [ 1 99  2 99  3 99  4  5]
--------------------------------------------------



### with 2D-arrays

In [62]:
# insertign along axis=0
arr2d_1=np.arange(1,10).reshape(3,3)

# insert a new row before index 1
new_row=np.array([999,999,999])
result=np.insert(arr2d_1,1,new_row,axis=0)
print(result)
print("-"*50)
print()

# insert multiple rows:
arr2d_2=np.arange(1,10).reshape(3,3)
print(f"arr2d_2: {arr2d_2}")
print("-"*50)

new_rows=np.arange(13,22).reshape(3,3)
result=np.insert(arr2d_2,[0,1,2],new_rows,axis=0)
print(f"result: {result}")
print("="*50)
print()

## inserting along axis=1
print('ALONG axis=1')
arr2d_3=np.arange(1,10).reshape(3,3)
print(f"arr_2d: {arr2d_3}")
print("-"*50)
print()

# insert a new column before index 1
new_column=np.array([10,11,12])
result=np.insert(arr2d_3,1,new_column,axis=1)
print("Insert column at position 1:")
print(f"result:{result}")
print("-"*50)
print()

# Insert multiple columns
new_cols = np.array([[10, 11],
                     [12, 13],
                     [14, 15]])
result = np.insert(arr2d_3, [1,2], new_cols, axis=1)
print("\nInsert multiple columns at position 2:")
print(f"result:{result}")
print("="*50)
print()

## Axis=None-Flattened insertion
arr2d_4=np.arange(1,7).reshape(2,3)

# inserting into flatened array
result=np.insert(arr2d_4,2,[99,100],axis=None)
print(f"result: {result}")

[[  1   2   3]
 [999 999 999]
 [  4   5   6]
 [  7   8   9]]
--------------------------------------------------

arr2d_2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
result: [[13 14 15]
 [ 1  2  3]
 [16 17 18]
 [ 4  5  6]
 [19 20 21]
 [ 7  8  9]]

ALONG axis=1
arr_2d: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------

Insert column at position 1:
result:[[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 12  8  9]]
--------------------------------------------------


Insert multiple columns at position 2:
result:[[ 1 10  2 11  3]
 [ 4 12  5 13  6]
 [ 7 14  8 15  9]]

result: [[  1   2  99 100]
 [  3   4   5   6]]


##### Common Mistakes: 

In [ ]:
# Mistake 1: Forgetting axis for 2D arrays
arr_2d = np.array([[1, 2], [3, 4]])
# Wrong: np.insert(arr_2d, 1, [5, 6])  # Flattens unexpectedly
# Correct:
result = np.insert(arr_2d, 1, [5, 6], axis=0)

# Mistake 2: Index out of bounds
arr = np.array([1, 2, 3])
# Wrong: np.insert(arr, 5, 99)  # IndexError
# Correct:
result = np.insert(arr, len(arr), 99)  # Insert at end

# Mistake 3: Shape mismatch
arr_2d = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6, 7])  # Wrong shape
# result = np.insert(arr_2d, 1, new_row, axis=0)  # ValueError
# Correct:
new_row = np.array([5, 6])  # Must match number of columns

# append()-
- allows adding values at end of an array.
- unlike python list's append, which modifies in-place, NumPy's append() creates a new array with the added elements.
- Syntax: np.append(arr,values,axis=___)
    - arr= input array
    - values= values to append(scalar or array-like)
    - axis= axis along which to append (None=flatten first)

In [64]:
# Basic use with 1D-array
import numpy as np

# appending single value
arr=np.array([1,2,3,4,5])
result=np.append(arr,90)
print(f"result: {result}")
print("-"*50)

result=np.append(arr,[99,100,101])
print(f"result: {result}")

result: [ 1  2  3  4  5 90]
--------------------------------------------------
result: [  1   2   3   4   5  99 100 101]


In [67]:
# appending at beginning (using insert)
# append() only adds at the end
arr=np.array([1,2,3])

# to add at the beginning, use insert()
result=np.insert(arr,0,99)
# or concatenate
result=np.concatenate([[99],arr])

### 2D-arrays-

In [71]:
import numpy as np
# along axis=0 (rows)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
# append a new row
new_row=np.array([7,8,9])
result=np.append(arr_2d,[new_row],axis=0)
print(f"result: {result}")
print("-"*50)

# append multiple rows
new_rows=np.array([[7,8,9],[10,11,12]])
result=np.append(arr_2d,new_rows,axis=0)
print("\nAppend multiple rows:")
print(result)
print("-"*50)
print()

 # appending along axis=1
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
new_col = np.array([[7], [8]])  # Must have same number of rows
result = np.append(arr_2d, new_col, axis=1)
print("Append column:")
print(result)

# Axis=None - Flatten first
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Flatten then append
result = np.append(arr_2d, [99, 100], axis=None)
print(result)  # [1, 2, 3, 4, 5, 6, 99, 100]


result: [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------

Append multiple rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Advanced techniques: 

In [74]:
## appending with different shapes

# 2D-arrays
arr=np.array([[1,2],[3,4]])

# append row- must have same number of columns
new_row=np.array([[5,6]])
result=np.append(arr,new_row,axis=0)
print(f"result: {result}")
print("-"*50)

# append column- must have same number of rows
new_col=np.array([[5],[6],[7]])
result= np.append(result,new_col,axis=1)
print(result)

## conditional appending

# filtering and appending
data=np.array([10,25,30,45,50,60,75])
threshold=40

# appending only values above threshold
high_values=np.array([])
for value in data: 
    if value>threshold:
        high_values=np.append(high_values,value)
print("Values above threshold: ",high_values)
print("-"*50)

# or better approach by boolean indexing
high_values=data[data>threshold]
print("Better way: ",high_values)

result: [[1 2]
 [3 4]
 [5 6]]
--------------------------------------------------
[[1 2 5]
 [3 4 6]
 [5 6 7]]
Values above threshold:  [45. 50. 60. 75.]
--------------------------------------------------
Better way:  [45 50 60 75]


### IMPORTANT

In [ ]:
# 1. append() creates a COPY (not in-place)
arr = np.array([1, 2, 3])
result = np.append(arr, 4)
print("Original:", arr)   # [1, 2, 3] - unchanged
print("New array:", result)  # [1, 2, 3, 4]

# 2. Shape must match when using axis
arr_2d = np.array([[1, 2], [3, 4]])
# Wrong: np.append(arr_2d, [5, 6, 7], axis=0)  # Shape mismatch
# Correct:
new_row = np.array([[5, 6]])  # Must have 2 columns
result = np.append(arr_2d, new_row, axis=0)

# 3. axis=None flattens both arrays
arr_2d = np.array([[1, 2], [3, 4]])
result = np.append(arr_2d, [[5, 6]], axis=None)
print("Flattened:", result)  # [1, 2, 3, 4, 5, 6]

# 4. Can't append to empty 2D array without specifying shape
# Wrong: empty_2d = np.array([])
# Wrong: np.append(empty_2d, [[1, 2]], axis=0)  # Error
# Correct:
empty_2d = np.empty((0, 2))  # 0 rows, 2 columns
result = np.append(empty_2d, [[1, 2]], axis=0)

# Elements delete from ndarray in numpy

## 1. delete()-
- removes elements, rows, or columns from an array.
- returns a new array without modifying the original.
- Syntax: np.delete(arr,obj,axis=None)
     - arr= inputed array
     - obj= index/position to delete(int, slice, or list of indices)
     - axis= Axis along which to delete (None=flatten first)

In [80]:
# Basic use with 1D-array:
import numpy as np

## delete single element
# delete at specific index
arr= np.array([10,20,30,40,50])
result=np.delete(arr,2)
print(result)
print("original array unchanged: ",arr)
print("-"*50)

# delete first element
result= np.delete(arr,0)
print(result)
print("-"*50)

# delete last element
result=np.delete(arr,-1)
print(result)
print("="*50)
print()

## Deleting Multiple elements
arr=np.array([10,20,30,40,50,60,70])

# delete multiple specific indices
result=np.delete(arr,[1,3,5])
print(f"result: {result}")
print("-"*50)

# deleting using slice
result=np.delete(arr,slice(2,5))
print(f"result: {result}")
print("-"*50)

# delete range with step
result=np.delete(arr,slice(1,6,2))
print(f"result: {result}")
print("-"*50)

[10 20 40 50]
original array unchanged:  [10 20 30 40 50]
--------------------------------------------------
[20 30 40 50]
--------------------------------------------------
[10 20 30 40]

result: [10 30 50 70]
--------------------------------------------------
result: [10 20 60 70]
--------------------------------------------------
result: [10 30 50 70]
--------------------------------------------------


In [81]:
# deleting with boolean mask
arr=np.array([10,20,30,40,50])

# delete elements where condition is true
mask=arr>30
result=np.delete(arr,np.where(mask))
print(result)
print("-"*50)

# Alternative: simpler boolean indexing
result=arr[arr<=30]
print(result)
print("-"*50)

[10 20 30]
--------------------------------------------------
[10 20 30]
--------------------------------------------------


In [82]:
## Working with 2D-arrays
# Delete rows (axis=0)
arr2d_1=np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# delete single row
result=np.delete(arr2d_1,1,axis=0)  # delete row at index 1
print("Delete row 1:")
print(result)
print("-"*50)

# delete multiple rows
result=np.delete(arr2d_1,[0,2],axis=0)  # deletes rows 0 and 2
print("\nDelete rows 0 and 2:")
print(result)
print("-"*50)

# DELETE LAST ROW
result=np.delete(arr2d_1,-1,axis=0)
print("\nDelete last row:")
print(result)
print("-"*50)

Delete row 1:
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]
--------------------------------------------------

Delete rows 0 and 2:
[[ 4  5  6]
 [10 11 12]]
--------------------------------------------------

Delete last row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------


In [83]:
## Delete columns (axis=1)
arr2d=np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# delete single column
result=np.delete(arr2d,2,axis=1)  # delete column at index 2
print("Delete column 2:")
print(result)
print("-"*50)

# delete multiple columns
result=np.delete(arr2d,[0,3],axis=1)
print("\nDelete columns 0 and 3:")
print(result)
print("-"*50)

# delete first and last column
result=np.delete(arr2d,[0,-1],axis=1)
print("\nDelete first and last columns:")
print(result)
print("="*50)
print()

## Axis=None -- Flatten First
arr2d= np.array([[1, 2, 3],
                [4, 5, 6]])
# it flattens first then deletes
result=np.delete(arr2d,3,axis=None)
print(result)
print("-"*50)

Delete column 2:
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]
--------------------------------------------------

Delete columns 0 and 3:
[[ 2  3]
 [ 6  7]
 [10 11]]
--------------------------------------------------

Delete first and last columns:
[[ 2  3]
 [ 6  7]
 [10 11]]

[1 2 3 5 6]
--------------------------------------------------


In [89]:
# Practical examples

## 1. Removing Outliers
data=np.array([10, 12, 15, 100, 13, 14, 200, 11, 16])

# calculating Z-scores
mean=np.mean(data)
std=np.std(data)
z_scores=np.abs((data-mean)/mean)

# remove outliers (z-scores>2)
outlier_indices=np.where(z_scores>2)[0]
cleaned_data=np.delete(data,outlier_indices)
print("Original data:", data)
print("Outlier indices:", outlier_indices)
print("Cleaned data:", cleaned_data)
print("-"*50)

## 2. Removing duplicate rows
# dataset with duplicate rows
dataset=np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],  # Duplicate
                   [7, 8, 9],
                   [4, 5, 6]])  # Duplicate

# find unique rows and keep first occurence
_, unique_indices = np.unique(dataset, axis=0, return_index=True)
unique_indices = np.sort(unique_indices)
deduplicated = dataset[unique_indices]
print("Original dataset:\n", dataset)
print("\nDeduplicated:\n", deduplicated)
print("-"*50)

# Alternative using delete(remove duplicates)
duplicate_mask=np.zeros(len(dataset),dtype=bool)
for i in range(len(dataset)):
    if i not in unique_indices:
        duplicate_mask[i]=True
dedup_v2=np.delete(dataset,np.where(duplicate_mask),axis=0)
print(f"dedup_v2: {dedup_v2}")

Original data: [ 10  12  15 100  13  14 200  11  16]
Outlier indices: [6]
Cleaned data: [ 10  12  15 100  13  14  11  16]
--------------------------------------------------
Original dataset:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Deduplicated:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
dedup_v2: [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Advanced Techniques


In [94]:
## 1. Delete with Slices and Steps
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# delete every 3rd element
result=np.delete(arr,slice(2,None,3))
print(result)  
print("-"*50)

# delete range with step
result=np.delete(arr,slice(1,8,2))
print(result)
print("-"*50)

## 2. Conditional deletion with np.where()
arr=np.array([10, 25, 30, 45, 50, 65, 70])

# delete elements where value is between 30 and 60
indices_to_delete=np.where((arr >= 30) & (arr <= 60))[0]
result=np.delete(arr,indices_to_delete)
print(result)
print("-"*50)

# Delete elements that are multiples of 5
indices=np.where(arr%5==0)[0]
result=np.delete(arr,indices)
print(f"result: {result}")
print("-"*50)

## 3. Delete multiple ranges
arr=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Create list of indices to delete
to_delete=[]
to_delete.extend(range(1,3))
to_delete.extend(range(5,8))

result=np.delete(arr,to_delete)
print(f"result: {result}")
print("-"*50)

[0 1 3 4 6 7 9]
--------------------------------------------------
[0 2 4 6 8 9]
--------------------------------------------------
[10 25 65 70]
--------------------------------------------------
result: []
--------------------------------------------------
result: [ 10  40  50  90 100]
--------------------------------------------------


#### delete() vs Masking vs Boolean Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Method 1: delete()
result1 = np.delete(arr, [2, 5, 7])

# Method 2: Boolean indexing (often simpler)
mask = np.ones(len(arr), dtype=bool)
mask[[2, 5, 7]] = False
result2 = arr[mask]

# Method 3: List comprehension (slow, not recommended)
result3 = np.array([x for i, x in enumerate(arr) if i not in [2, 5, 7]])

print("delete():", result1)
print("Masking:", result2)
print("Same result:", np.array_equal(result1, result2))  # True

#### Important

In [ ]:
# 1. delete() returns a COPY
arr = np.array([1, 2, 3])
result = np.delete(arr, 1)
print("Original unchanged:", arr)  # [1, 2, 3]
print("New array:", result)        # [1, 3]

# 2. Axis is important for 2D arrays
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
# Wrong: np.delete(arr_2d, 1)  # Flattens by default
# Correct:
result = np.delete(arr_2d, 1, axis=0)  # Delete row 1

# 3. Deleting non-existent index raises error
arr = np.array([1, 2, 3])
# np.delete(arr, 5)  # IndexError: index 5 is out of bounds

# 4. When using list, order doesn't matter
arr = np.array([10, 20, 30, 40, 50])
result = np.delete(arr, [4, 1, 3])  # Indices sorted automatically
print(result)  # [10, 30]

# 5. Deleting from empty array
empty = np.array([])
# result = np.delete(empty, 0)  # IndexError
# Better to check first:
if len(empty) > 0:
    result = np.delete(empty, 0)

# Usage of dot() function for matric multiplication
- dot() performs matrix multiplication efficiently.
- used in fields: linear algebra, signal processing, and machine learning.
- dot() multiplies 2 arrays resulting in matrix multiplication when dealing with multi-dimensional arrays.
- this function is crucial for tasks such as solving systems of linear equans, transforming data in neural networks, and performing various matrix operations required in scientific computing and data analysis.
- Syntax: np.dot(a,b,out=None)

In [95]:
import numpy as np
arr1=np.arange(1,5).reshape(2,2)
arr2=np.arange(11,15).reshape(2,2)
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print("using numpy function")
print(np.dot(arr1,arr2))
print("Using ndarray object")
print(arr1.dot(arr2))

arr1: [[1 2]
 [3 4]]
arr2: [[11 12]
 [13 14]]
using numpy function
[[37 40]
 [85 92]]
Using ndarray object
[[37 40]
 [85 92]]


# Usage of linalg module in numpy-
- for performing linear algebra operations in numpy like:
    - finding matrix inverse
    - power
    - determinant
    - and solving linear algebra equations.

In [97]:
import numpy as np
print("Finding matrix inverse")
arr1=np.arange(11,15).reshape(2,2)
print(f"inverse of arr1:\n {np.linalg.inv(arr1)}") # valid only for square matrices
print("="*50)
print(f"power of arr1:\n {np.linalg.matrix_power(arr1,0)}") # valid only for square matrices
print("="*50)
print(f"finding power of a matrix with n<0:\n {np.linalg.matrix_power(arr1,-2)}") # first inverse then power
print("="*50)
print(f"determinant of matrix:\n {np.linalg.det(arr1)}") # valid only for square matrices
print("="*50)
arr2=np.array([[1,1],[2,6]])
arr3=np.array([6,24])
print(f"solving linear algebra equations:\n {np.linalg.solve(arr2,arr3)}")

Finding matrix inverse
inverse of arr1:
 [[-7.   6. ]
 [ 6.5 -5.5]]
power of arr1:
 [[1 0]
 [0 1]]
finding power of a matrix with n<0:
 [[ 88.   -75.  ]
 [-81.25  69.25]]
determinant of matrix:
 -1.9999999999999931
solving linear algebra equations:
 [3. 3.]
